language: python
python:
- '2.7'
install:
- pip install -e .
- pip install coveralls
- pip install sure
- pip install py-inspector
script:
- rm -rf .coverage
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: lojaintegrada
  on:
    tags: true
    repo: lojaintegrada/LI-Pagador-Deposito
    all_branches: true
  password:
    secure: mcVNi+TWw1SZIfU3/Guftu0E02Ii2umBvlCyK1vhIE0pn6sGwCNl18viApOeELp/Towp0fsq9KViI7e0ug3x+vhAv1894hfg7Qmx6iv0qYbdLfGG8u+w7hbFJ2W+SvzaV1QtNSLuSLB3UeuzbI3RVLWATQ4iWnlTGoZmUQQWz94=
notifications:
  email:
    recipients:
    - contato@awsli.com.br
    - marcio.duarte@lojaintegrada.com.br
  hipchat:
    rooms:
      secure: YZwRhPLgK9gj0xXdJzSKNbrfEfupm8bLm0HiOQHGXsE33HbOvgoLQkh5E07IWjiJi0RkpHiAP/pp/gqmp+pjdJ58uYnoYOzgcnzmzna/reqIdGvfVsueE/7wotLjnUs/WGDcDWR2XqcqrPMGHZ0WTmSoZNkRNmKCxCquZ670sec=
    template:
      - '%{result} - %{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}) (<a href="%{build_url}">Detalhes</a>/<a href="%{compare_url}">Alterações</a>)'
    format: html